- name: Power on Servers
  hosts: all
  tasks:
    - name: Power on Alpha
      command: ssh admin@192.168.1.200 power on arg1
      register: alpha
    - name: Power on Beta
      command: ssh admin@192.168.1.201 power on arg1
      register: beta      