---
- hosts: hp_servers
  gather_facts: no
  connection: local
 
  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: HP | Power
    ios_command:
      provider: "{{ provider }}"
      commands:
        - power on
    register: power

  - debug: msg="{{ power.stdout }}"            